AllCops:
  TargetRubyVersion: 2.6.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 35

Metrics/LineLength:
  AllowURI: true
  Max: 130

Metrics/MethodLength:
  Max: 15
